### ISSUE TITLE
memory issure

### ISSUE THREAD

**Issue by coco40725** [mdonoghoe/logbin#6]
Hi, sorry to bother you.

Recently, I tried to use this package logbin to fit the log binomial regression, and the formula is:
Y~ x1+x2+....+x50
 Y is the binary data, and x1,x2,...x50 are the multinomial data {0,1,2}. The observation number of data is 80,000.

However, when I use the logbin function `fit = logbin(y~x1+x2+....+x50)` , I got the error :
**Error: cannot allocate vector of size 4194304.0 Gb**

I am not sure why  we need such large memory to execute the logbin function.

Do you have any suggestions to deal with this issue?

**Comment by mdonoghoe** [comment]
Hi,

Are you using logbin v2.0.5?

In previous versions, this kind of memory error could occur because when using `method = "cem"`, it would attempt to create the full list of the 2^50 (=10^15) possible parameter subspaces. In v2.0.5 the `itertools2` package is used so that this is [avoided](https://github.com/mdonoghoe/logbin/commit/6676bbc3cb0dedd9c2965816f4419cd2af128e9f).

If you are using v2.0.5, I'm not sure what the cause might be. But you could potentially avoid it by using `fit = logbin(y~x1+x2+....+x50, method = "em")`, which does everything in a single step.

Let me know how you go.

**Comment by coco40725** [comment]
HI, 
It turns out I was using old version 2.0.4, no wonder I get the memory issue!

However, even in the newest version 2.0.5, I find that `method = "cem"` still have some problems, instead of the memory error, it show the error 
```
error: Error in logbin.cem(mt = y ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 +  : 
The number of parameter subspaces is larger than R can handle (see .Machine$integer.max). Make some terms monotonic or use method = "em"
```
It seems that `method = "cem"` still cannot handle the variables with very large large number in version 2.0.5.

And of course, I have tried `method = "em"`, and as you said , this method perfectly avoid the memory issue. 

It works!! Thank you!

By the way, sometimes I will get the MLE boundary error, like this:

`MLE on boundary of parameter space, cannot use asymptotic covariance matrix 
`
So far, I have tried to lower down the value of  bound.tol and  epsilon, but it show the error :
`nplbin: algorithm did not converge`.
Do you have any suggestions to avoid this error?

**Comment by mdonoghoe** [comment]
Ok, yes in this case `"cem"` will not run at all, since R cannot even store the number of parameter subspaces as an integer, let alone the list of these parameter subspaces. Version 2.0.5 can avoid the memory error if the _list_ is too large (by not storing the list), but not if the number of _items_ in the list is itself is too large. Even if it could run, and every subspace took just 1 second to fit, you would require [over 35 million years](https://www.wolframalpha.com/input/?i=2%5E50+seconds), so it's probably a good thing that it doesn't start!

The boundary message is a warning rather than an error. The algorithm has reached the MLE (i.e. a valid result), but it is on the boundary of the parameter space (some [covariate combinations](https://www.jstatsoft.org/article/view/v086i09) give a fitted probability of 1), so you can't use the usual methods to find an estimate of the covariance matrix. You can use bootstrapping ([ref](https://doi.org/10.1111/anzs.12131)) or a specialised approach ([ref](https://doi.org/10.1080/03610926.2017.1402045)) to estimate covariance if the MLE is on the boundary. These aren't implemented in `logbin` at the moment.

Lowering `epsilon` will not avoid the boundary warning unless you have a reason to think that you are getting 'false convergence'. To avoid the non-convergence message, you would also need to increase `maxit` in order to give the algorithm more time to meet the stricter criterion. Lowering `bound.tol` could avoid the boundary warning but I don't recommend it unless you have good reason --- and avoiding the warning is not a good reason on its own.
